### ISSUE TITLE
Problem with compose

### ISSUE THREAD

**Issue by janaxhell** [mgdigital/rarbg-selfhosted#1]
Hi, coming from Reddit.
This is my compose that produces an error on line 3

```
version: "3.7"
services:
  rarbg-selfhosted:
    container_name: rarbg-selfhosted
    build:
      context: .
    environment:
      - "PATH_SQLITE_DB=/rarbg_db.sqlite"
      - "PATH_TRACKERS=/trackers.txt"
    volumes:
      - "/srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/rarbg-selfhosted/rarbg_db.sqlite:/rarbg_db.sqlite"
      - "/srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/rarbg-selfhosted/trackers.txt:/trackers.txt"
    ports:
      - "3333:3333"
```

Can you tell what's wrong?
